# Searching for the category

For this code along we are only going to use the products DataFrame. However, if you believe there is information in other tables that can help to create categories, please feel free to explore.

In [2]:
import pandas as pd

In [3]:
# products_cl.csv
url = "https://drive.google.com/file/d/1IPnKYLSnrST0HBZMeSeNrhFfWU31QvwB/view?usp=drive_link"
path = "https://drive.google.com/uc?export=download&id="+url.split("/")[-2]
products_cl = pd.read_csv(path,  dtype={"type": str})

In [4]:
product_category_df = products_cl.copy()

In [5]:
product_category_df.head()

,sku,name,desc,price,in_stock,type
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364

## 1.&nbsp; Category creation by search term
Let's start by creating a column `category`. For now we'll fill this column with a blank string `""`.

In [6]:
product_category_df["category"] = ""
product_category_df.head()

,sku,name,desc,price,in_stock,type,category
0,RAI0007,Silver Rain Design mStand Support,Aluminum support compatible with all MacBook,59.99,1,8696,
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,
2,APP0025,Mighty Mouse Apple Mouse for Mac,mouse Apple USB cable.,59.00,0,1387,
3,APP0072,Apple Dock to USB Cable iPhone and iPod white,IPhone dock and USB Cable Apple iPod.,25.00,0,1230,
4,KIN0007,Mac Memory Kingston 2GB 667MHz DDR2 SO-DIMM,2GB RAM Mac mini and iMac (2006/07) MacBook Pr...,34.99,1,1364,

We can find all the products with certain words in their `description` using `.loc[]` and `.str.contains()`. Here we'll look at all the items that have the word `keyboard` in their description.

In [7]:
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False)]

,sku,name,desc,price,in_stock,type,category
1,APP0023,Apple Mac Keyboard Keypad Spanish,USB ultrathin keyboard Apple Mac Spanish.,59.00,0,13855401,
15,MOS0021,Clearguard Moshi MacBook Pro and Air,Keyboard Protector MacBook Pro 13-inch Retina ...,24.95,0,13835403,
24,APP0277,Apple Wireless Keyboard Keyboard (OEM) Mac,Ultrathin keyboard Apple Bluetooth Spanish (un...,79.00,0,13855401,
64,HGD0012,Henge Docks Click keyboard support iMac,Base to hold the Apple Magic TrackPad and Wire...,29.00,0,8696,
365,LOG0084,Logitech Ultrathin Keyboard Cover Keyboard Cov...,Ultrathin cover and cover with Bluetooth keybo...,89.99,0,12575403,
...,...,...,...,...,...,...,...
9720,PAC2508,Replacement Magic Wireless Keyboard by Matias ...,Keyboard replacement service at the time of pu...,119.99,1,13855401,
9751,MTF0008,Mistify Clean Screens Natural 500ml.,Spray cleaning screens and keyboards.,14.99,1,12085400,
9796,ZAG0026-A,Open - Zagg Rugged Keyboard Folio iPad Messeng...,Case reconditioned keyboard and adjustable pos...,99.99,0,12575403,
9932,APP1472,Apple Magic Keyboard English International,English keyboard Mac and Apple iPad Ultrathin ...,119.00,1,13855401,
9945,TWS0106-A,Open - Twelve South Bridge Magic Keyboard for ...,Light reconditioned support to hold the Keyboa...,48.00,0,8696,

Next, we change the value in the category column to `keyboard` for all of these keyboard products.

In [8]:
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False), "category"] = "keyboard"

Let's take a look at the effect that had on the `category` column.

In [9]:
product_category_df["category"].value_counts()

category
            9903
keyboard      89
Name: count, dtype: int64

## 2.&nbsp; Category creation using regex
We can also use a product's `name` to select products for our categories.

In [10]:
product_category_df.loc[product_category_df["name"].str.contains("apple iphone", case=False)]

,sku,name,desc,price,in_stock,type,category
35,APP0308,AV Cable Adapter Apple iPhone iPad and iPod white,IPhone iPad iPod adapter and AV cable.,45.00,0,1230,
214,REP0100,Color change to White Apple iPhone 4,It is including parts and labor..,94.21,0,"1,44E+11",
215,REP0052,Color change to White Apple iPhone 4,It is including parts and labor..,94.21,0,"1,44E+11",
579,APP0675,Apple iPhone 5S 32GB Space Gray,New Free iPhone 5S 32GB (ME435Y / A).,559.00,0,NaN,
956,APP0823,Apple iPhone 6 16GB Silver,New iPhone 6 16GB Free (MG482QL / A).,639.00,0,NaN,
...,...,...,...,...,...,...,...
9790,AP20455,Like new - Apple iPhone 8 256GB Gold,Apple iPhone 8 reconditioned 256GB in Gold rea...,979.00,0,113291716,
9794,APP2482-A,Open - Apple iPhone 8 Plus 256GB Gold,Refurbished Apple iPhone 8 Plus 256GB Free Gold,1089.00,0,113281716,
9929,APP2477-A,Open - Apple iPhone 8 Plus 64GB Space Gray,Apple iPhone 8 Plus 64GB Space Gray,919.00,0,113281716,
9958,AP20467,Like new - Apple iPhone Silicone Case Cover 7 ...,Reconditioned silicone sleeve microfiber Apple...,45.00,0,11865403,
9969,AP20468,Like new - Apple iPhone Black Lightning Dock,Support base and refitted with dock connector ...,59.00,0,13615399,

Looks like we get a lot of accessories included in this search. We can refine this using a little regex. Here, we will add `.{0,7}` at the beginning of the search: this means we will find all `apple iphone`s that have 7 or less characters preceding the term "apple iphone" - if there's 8 characters preceding the search term, it won't be found. This should help refine our search by using the nomenclature of the DataFrame to our advantage.

If you feel unsure about regex, please use [regex101](https://regex101.com/). It's really useful for checking your code, and parts of other people's code that you're unsure about.

In [11]:
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False)]

,sku,name,desc,price,in_stock,type,category
579,APP0675,Apple iPhone 5S 32GB Space Gray,New Free iPhone 5S 32GB (ME435Y / A).,559.0,0,NaN,
956,APP0823,Apple iPhone 6 16GB Silver,New iPhone 6 16GB Free (MG482QL / A).,639.0,0,NaN,
961,APP0829,Apple iPhone 6 Plus 16GB Silver,New iPhone 6 Plus 16G Free (MGA92QL / A).,749.0,0,NaN,
962,APP0822,Apple iPhone 6 16GB Space Gray,New iPhone 6 16GB Free (MG472QL / A).,639.0,0,NaN,
963,APP0825,Apple iPhone 6 64GB Space Gray,New iPhone 6 64GB Free (MG4F2QL / A).,749.0,0,NaN,
...,...,...,...,...,...,...,...
9585,APP1634-A,Open - Apple iPhone 7 Plus 32GB Black,New 32GB Apple iPhone 7 Plus Free Black,779.0,0,85651716,
9587,APP2540-A,Open - Apple iPhone Leather Folio X Baya,Leather case with box and official cover Apple,109.0,0,11865403,
9714,APP2562-A,Open - Apple iPhone Leather Case Cover Red,Reconditioned skin sheath official Apple desig...,45.0,0,11865403,
9794,APP2482-A,Open - Apple iPhone 8 Plus 256GB Gold,Refurbished Apple iPhone 8 Plus 256GB Free Gold,1089.0,0,113281716,
9929,APP2477-A,Open - Apple iPhone 8 Plus 64GB Space Gray,Apple iPhone 8 Plus 64GB Space Gray,919.0,0,113281716,

Now we can use the same trick as before to set the category - selecting the `category` column and setting it to the string of our choice.

In [12]:
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False), "category"] = "smartphone"

In [13]:
product_category_df["category"].value_counts()

category
              9634
smartphone     269
keyboard        89
Name: count, dtype: int64

## 3.&nbsp; One product with multiple categories
A product may fit into multiple categories. To help us create multiple categories for one product, we will use the python addition assignment `+=`. The addition assignment is a shorthand way to add something (number, string, etc...) to a variable without changing the variable name.

Let's have a look at a couple of examples.

In [14]:
a = 10
a = a + 5
a

15

In [15]:
a = 10
a += 5
a

15

In [16]:
b = "Tyrannosaurus"
b = b + " rex"
b

'Tyrannosaurus rex'

In [17]:
b = "Tyrannosaurus"
b += " rex"
b

'Tyrannosaurus rex'

Now let's look at how this can help us in our category creation.

First, we'll reset all the values in the category column to an empty string `""`.

In [18]:
product_category_df["category"] = ""

Now, let's create some categories and utilise the addition assignment.

In [19]:
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False), "category"] += ", keyboard"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False), "category"] += ", smartphone"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple ipod", case=False), "category"] += ", ipod"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple ipad|tablet", case=False), "category"] += ", tablet"
product_category_df.loc[product_category_df["name"].str.contains("imac|mac mini|mac pro", case=False), "category"] += ", desktop"

In [20]:
product_category_df["category"].value_counts()

category
                       8362
, desktop               923
, tablet                307
, smartphone            269
, keyboard               83
, ipod                   42
, keyboard, tablet        4
, keyboard, desktop       2
Name: count, dtype: int64

As you can see, some products now have 2 categories instead of just one. At the end, you can use your skills with string to tidy up the opening comma and space in the `category` column.

# Challenge. Your categories
Now it's your turn. We'll reset the Dataframe so that no categories exist, and it's up to you to create the categories based on keywords in the name and description. Feel free to go wild and make as many categories as you like.
* Remember you can also use regex to refine your searches.
* Remember you can use the or operator `|` to search for multiple terms at once.
* Remember to tidy up any untidy strings at the end.

In [21]:
# resetting to original import
product_category_df = products_cl.copy()

In [36]:
product_category_df["category"] = ""
product_category_df.loc[product_category_df["name"].str.contains("Apple", case=False), "category"] += ", "+"Apple"
product_category_df.loc[product_category_df["name"].str.contains("Mac", case=False), "category"] += ", "+"Mac"
product_category_df.loc[product_category_df["desc"].str.contains("keyboard", case=False), "category"] += ", "+"keyboard"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple iphone", case=False), "category"] += ", "+"smartphone"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple ipod", case=False), "category"] += ", "+"ipod"
product_category_df.loc[product_category_df["name"].str.contains("^.{0,7}apple ipad|tablet", case=False), "category"] += ", "+"tablet"
product_category_df.loc[product_category_df["name"].str.contains("imac|mac mini|mac pro", case=False), "category"] += ", "+"desktop"
product_category_df.loc[product_category_df["name"].str.contains("stand", case=False), "category"] += ", "+"stand"
product_category_df.loc[product_category_df["name"].str.contains("USB", case=False), "category"] += ", "+"USB"
product_category_df.loc[product_category_df["name"].str.contains("Cable", case=False), "category"] += ", "+"Cable"
product_category_df.loc[product_category_df["name"].str.contains("Mouse", case=False), "category"] += ", "+"Mouse"
product_category_df.loc[product_category_df["name"].str.contains("headphones", case=False), "category"] += ", "+"Headphones"
product_category_df.loc[product_category_df["name"].str.contains("Docking Station", case=False), "category"] += ", "+"Docking Station"
product_category_df.loc[product_category_df["name"].str.contains("Adapter", case=False), "category"] += ", "+"Adapter"
product_category_df.loc[product_category_df["name"].str.contains("HDMI", case=False), "category"] += ", "+"HDMI"
product_category_df.loc[product_category_df["name"].str.contains("DVI", case=False), "category"] += ", "+"DVI"
product_category_df.loc[product_category_df["name"].str.contains("FireWire", case=False), "category"] += ", "+"FireWire"
product_category_df.loc[product_category_df["name"].str.contains("Mount", case=False), "category"] += ", "+"Mount"
product_category_df.loc[product_category_df["name"].str.contains("Case", case=False), "category"] += ", "+"Case"
product_category_df.loc[product_category_df["name"].str.contains("Repair", case=False), "category"] += ", "+"Repair"
product_category_df.loc[product_category_df["name"].str.contains("Router", case=False), "category"] += ", "+"Router"
product_category_df.loc[product_category_df["desc"].str.contains("Desktop support", case=False), "category"] += ", "+"Support"
product_category_df.loc[product_category_df["name"].str.contains("cleaner", case=False), "category"] += ", "+"cleaner"
product_category_df.loc[product_category_df["name"].str.contains("tablet", case=False), "category"] += ", "+"Tablet"
product_category_df.loc[product_category_df["name"].str.contains("charger", case=False), "category"] += ", "+"Charger"
product_category_df.loc[product_category_df["name"].str.contains("stylus", case=False), "category"] += ", "+"Stylus"
product_category_df.loc[product_category_df["name"].str.contains("license", case=False), "category"] += ", "+"License"
product_category_df.loc[product_category_df["name"].str.contains("iRig", case=False), "category"] += ", "+"iRig"
product_category_df.loc[product_category_df["name"].str.contains("gloves", case=False), "category"] += ", "+"Gloves"
product_category_df.loc[product_category_df["name"].str.contains("Switch", case=False), "category"] += ", "+"Switch"
product_category_df.loc[product_category_df["name"].str.contains("fitbit", case=False), "category"] += ", "+"Fitbit"
product_category_df.loc[product_category_df["name"].str.contains("battery", case=False), "category"] += ", "+"battery"

In [37]:
product_category_df.loc[product_category_df["category"]==""].head(40)

,sku,name,desc,price,in_stock,type,category
32,BEL0070,Music Receiver Belkin iPhone music receiver,Music Receiver iPhone iPad and iPod Touch for ...,49.99,0,11905404,
44,MOB0009,Mobee Magic Numpad for the Magic Trackpad,3 Numeric for Magic Trackpad stickers.,29.49,0,12355400,
62,WIT0009,Withings Wireless Scale Scale iPhone iPad & iP...,Scale WS-30 iPhone iPad and iPod Touch applica...,99.95,0,11905404,
73,SYN0051,Sliding Rail kit synology 2U sliding rails,Shelf rail kit Synology RackStation.,102.49,0,1404,
80,MOS0073,Moshi iVisor AG Retina iPad Protector (3G / 4G...,Retina iPad Protector free air bubbles.,29.95,0,14035403,
91,GRT0249,Griffin Helo TC Assault Helicopter iPhone iPad...,Remote Control Helicopter iPhone iPad and iPod...,59.99,0,12285400,
93,WAC0054,Wacom Bamboo Pen (pen parts for CTL-470K),Replacement pen for CTL-470K.,34.90,0,1229,
94,WAC0055,Wacom Intuos Professional Accessory Kit,Intuos accessory kit.,24.90,0,101781405,
129,DLK0008,D-Link DCS-932L Wireless IP Camera Cloud,Wireless network camera day and night home wit...,79.99,0,9094,
130,DLK0009,D-Link DCS-942L Wireless IP Camera Cloud,security camera with Wi-Fi or Ethernet night v...,169.99,0,9094,
167,NTE0010,NewerTech iPhone Kit tools,7 Kit tools needed for iPhone 4 / 4S,15.99,1,12645406,
198,MUV0045,Muvit iPhone in September matte Screen Savers ...,Set 2 screen protectors for iPhone matte finis...,8.99,0,13555403,
199,MUV0047,Muvit MiniGel Funda iPhone 5 / 5S White,Rubber cover iPhone 5 / 5S.,8.99,0,11865403,
252,GRT0262,Griffin Adidas miCoach armband iPhone 5 / 5S a...,Bracelet iPhone 5 / 5S and iPod Touch nylon sp...,29.99,0,5405,
267,GRT0267,Griffin Slim Folio iPad mini / black Retina,Funda iPad mini leather imiatación support.,39.99,0,12635403,
296,DLK0029,D-Link DCS-5222L surveillance camera,surveillance camera home with 10x zoom feature...,265.99,0,9094,
297,WAH0007,Wahoo Fitness BlueSC cadence and speed sensor,iPhone wireless sensor cadence and speed for c...,59.99,1,11905404,
298,WAH0008,Wahoo Fitness Blue HR heart rate monitor iPhon...,Wireless heart rate monitor iPhone iPad and iP...,79.99,0,11905404,
299,MOS0085,Moshi iVisor XT protector iPhone / 5s / 5 white,IPhone Protector SE / 5s / 5 anti glare.,24.95,0,13555403,
300,MOS0086,Moshi iVisor XT protector iPhone / 5s / 5c / 5...,IPhone Protector SE / 5s / 5 anti glare.,24.95,0,13555403,
301,PAR0009,Parrot Minikit + bluetooth hands free,iPhone bluetooth handsfree speaker car.,59.99,0,5398,
337,NTE0056,NewerTech Complete set of 14 tools,portable kit of 14 tools for Mac and PC.,23.99,0,14305406,
339,KEN0079,Kensington Expert Presenter Green Laser Pointer,laser pointer 10X bright green.,76.99,0,1229,
341,KEN0080,Kensington Presenter Expert green laser pointe...,laser pointer green + USB 4GB 10 times brighter,89.99,0,1229,
342,KEN0081,Kensington Expert Presenter Red Laser Pointer,Red laser pointer for presentations color.,49.99,0,1229,
366,KEN0096,Kensington Evap Water Rescue Pouch bag wet sal...,Salvation bag for iPhone and iPod exposed to m...,19.99,0,11905404,
369,SNN0021,Sonnet Tempo SSD 6Gb / s SATA SSD PCIe 2.0 con...,PCI Express SSD.,119.79,0,1276,
383,OWC0072,OWC Mercury Electra 6G SSD 240GB,240GB SSD hard drive 9.5mm SATA III Mac and PC.,164.99,0,12215397,
384,OWC0123,OWC Mercury Electra 6G 480GB SSD 7mm,SSD 480GB SATA HDD 7mm III Mac and PC.,278.99,0,12215397,
385,KIN0078,Kingston V300 SSD Disk 120GB,SSD 120GB SATA Hard Drive Mac and PC III.,60.00,0,12215397,
386,KIN0079,Kingston V300 SSD Disk 240GB,SSD 240GB SATA Hard Drive Mac and PC III,94.99,0,12215397,
388,KAN0012,Kanex meDrive Server,Reduced size USB server.,69.95,0,1334,
391,MOS0084,Moshi iVisor XT protector iPad mini / black Re...,IPad Mini Screen Protector bubble free.,22.99,0,14035403,
393,MOS0083,Moshi iVisor XT protector iPad mini / White Re...,IPad Mini Screen Protector bubble free.,35.00,0,14035403,
399,WIT0011,Withings Smart Body Analyzer scale black,Scale iPhone iPad and iPod Touch application f...,149.99,0,11905404,
413,NTE0049,NewerTech miniStack MAX + DVD recorder / CD,Housing for Mac Mini with recorder and card re...,235.99,1,12995397,
414,NTE0050,NewerTech miniStack MAX + Recorder BLURAY / DV...,Housing for Mac Mini with DVD and Bluray DVD r...,337.99,0,12995397,
415,RUN0007,Runware RunAlyzer Blue Ribbon cardio bluetooth,Band wireless heart rate monitor iPhone iPad a...,69.99,0,11905404,
417,IKM0024,IK Multimedia Studio iKlip iPad support,Support iPad 1 2 3 4 and Air multiposition table.,36.59,0,1216,
420,STM0047,STM Bags iPad Gray Linear Bandolier,IPad shoulder bag with adjustable strap.,49.99,0,12635403,

## 4.&nbsp; [BONUS] Using `type` to create categories
There could be another way to create categories, but this one you'll have to explore this one alone.

We have the mysterious column `type` in the `products` table. This could potentially be ready-made categories labelled with numbers instead of words. Let's investigate.

In [24]:
category_type_df = products_cl.copy()

Here are the `type`s that have the most products.

In [25]:
category_type_df.groupby("type").count().nlargest(10, "sku")

           sku  name  desc  price  in_stock
type
11865403  1057  1057  1057   1057      1057
12175397   939   939   939    939       939
1298       783   783   783    783       783
11935397   562   562   562    562       562
11905404   454   454   454    454       454
1282       373   373   373    373       373
12635403   362   362   362    362       362
13835403   269   269   269    269       269
5,74E+15   247   247   247    247       247
1364       216   216   216    216       216

Let's have a look at the first `type` to see if we can make categories from this column.

In [26]:
category_type_df.loc[category_type_df["type"] == "11865403"].sample(10)

,sku,name,desc,price,in_stock,type
4879,JMO0060-A,Open - Just Mobile Phone Case Skin AluFrame 6 ...,Aluminum and leather iPhone 6 / 6S,39.99,0,11865403
9075,LIF0132,NEXT LifeProof iPhone Case 8 Plus / 7 Plus Black,adds extra protection to your iPhone with Life...,79.99,0,11865403
5108,GRT0439,Griffin Survivor iPhone Case Journey 7 / 6s / ...,Cast and impact resistant padded case for iPho...,29.99,0,11865403
8755,APP2563,Apple iPhone Leather Case X Case Blue Cosmos,Leather case Apple official,59.00,1,11865403
9480,MOS0205-A,Open - Moshi iGlaze XT Case iPhone 7/8 Transpa...,Reconditioned sleeve transparent ultra thin wi...,30.00,0,11865403
5432,GRT0446,Griffin Survivor iPhone Case Journey 8 Plus / ...,rugged case with shock dispersion system for i...,29.99,0,11865403
8244,SPE0205,Presidio Speck Case iPhone X Black,protective case with anti-impact polycarbonate...,24.95,1,11865403
3009,OTT0099,Strada OtterBox iPhone Case Leather Folio 6 / ...,Resistant cover card slot for iPhone 6.,49.99,0,11865403
6697,STK0013,Stikgo iPhone Case + Car Support 8 Plus / 7 Pl...,Holster + Magnetic car holder for iPhone 8 Plu...,19.99,0,11865403
1061,MOS0139,Sensecover Moshi Case iPhone 6 / 6S Black,Cover with touch sensor to answer calls withou...,45.00,0,11865403

Looks like this is a category of phone cases.

Let's have a look at the 2nd largest type to see if that's also a clear category.

In [27]:
category_type_df.loc[category_type_df["type"] == "12175397"].sample(10)

,sku,name,desc,price,in_stock,type
8345,PAC2353,DS418J Synology NAS Server | 12TB (4x3TB) Seag...,4 bay NAS server capable of transmitting H.265...,874.95,1,12175397
8592,PAC2233,Synology DS218 + NAS Server | 6GB RAM | 8TB (2...,NAS storage server integrated with special foc...,744.98,1,12175397
3676,SYN0137,Synology DS216 + NAS server Mac and PC,Server NAS high performance processor 2 cores.,332.99,0,12175397
7769,PAC1698,Pack QNAP TS-251A NAS Server | 16GB RAM | Seag...,NAS with 16GB of RAM and 16TB (2x8TB) Seagate ...,1211.65,0,12175397
1081,PAC0518,Synology DS115j Pack | Seagate 4TB IronWolf,Synology DS115j NAS Server Pack + 4TB Seagate ...,271.98,0,12175397
3842,PAC1381,Pack QNAP TS-228 | WD 6TB Network,NAS + 6TB (2x3TB) WD Network for Mac and PC.,398.99,0,12175397
9006,QNA0257,Qnap NAS server TS-231P2-4G,NAS with 4GB of RAM and 3 USB ports for Mac an...,309.99,1,12175397
3498,PAC1352,Synology Pack DS416J | Seagate 12TB IronWolf,Synology Pack + 12TB (4x3TB) IronWolf Seagate ...,754.95,0,12175397
3378,PAC1339,Pack QNAP TS-453A | 8GB RAM | Seagate 16TB Iro...,Pack NAS QNAP TS-453A with 8GB of RAM + memory...,1420.55,0,12175397
9866,SYN0172-A,Open - Synology DS918 + NAS Server 4GB Ram Mac...,Reconditioned Plus Series of NAS Enterprise Se...,574.99,0,12175397

Looks like this category is full of servers.

I wonder how many `type`s account for most of our products?

In [28]:
n = 30
print(f"With the {n} largest types, we account for {((category_type_df.groupby('type').count().nlargest(n, 'sku')['sku'].sum()) / (category_type_df.shape[0]) * 100).round(2)}% of all products.")

With the 30 largest types, we account for 78.4% of all products.

Looks like we can simply investigate 30 types and set the categories, then the remaining 20% of products can have the category `other`.

Use the skills you learnt above to change the category for each type.

In [29]:
category_type_df.groupby("type").count().nlargest(30, "sku")

           sku  name  desc  price  in_stock
type
11865403  1057  1057  1057   1057      1057
12175397   939   939   939    939       939
1298       783   783   783    783       783
11935397   562   562   562    562       562
11905404   454   454   454    454       454
1282       373   373   373    373       373
12635403   362   362   362    362       362
13835403   269   269   269    269       269
5,74E+15   247   247   247    247       247
1364       216   216   216    216       216
12585395   190   190   190    190       190
1296       187   187   187    187       187
1325       183   183   183    183       183
5384       178   178   178    178       178
1433       171   171   171    171       171
12215397   170   170   170    170       170
5398       159   159   159    159       159
1,02E+12   130   130   130    130       130
1,44E+11   129   129   129    129       129
57445397   129   129   129    129       129
1334       115   115   115    115       115
2158       107   107   107    107       107
2449       107   107   107    107       107
12655397   105   105   105    105       105
1229       104   104   104    104       104
12995397    95    95    95     95        95
1515        85    85    85     85        85
13615399    78    78    78     78        78
13555403    75    75    75     75        75
1405        75    75    75     75        75

In [30]:
category_type_df["category"] = ""

Ok the below looks for the most popilar uncategorized type. We just run it over and over as we add categories.

In [31]:
top_type=category_type_df.loc[category_type_df["category"]=="", :].groupby("type").count().nlargest(1, "sku")
category_type_df.loc[(category_type_df["type"] == top_type.index[0]) & (category_type_df["category"] == ""),:].head(50)

,sku,name,desc,price,in_stock,type,category
18,MUV0009,Muvit Back Clear Case iPhone 4 / 4S Transparent,Case iPhone 4 / 4S polycarbonate.,9.99,0,11865403,
37,MUV0023,Extreme Muvit iPhone and iPod BikeMount sleeve...,IPhone and iPod support sleeve waterproof App ...,35.90,0,11865403,
132,ROL0010,Rollei Chest Mount iPhone 4 / 4S,Case iPhone 4 / 4S for sport.,49.99,0,11865403,
194,KEN0059,Kensington Soft Case cover iPhone 5 / 5S black,Soft Case iPhone 5 / 5S.,14.99,0,11865403,
195,KEN0062,Kensington Thin Back Case iPhone 5 / 5S Gray,Back Case iPhone 5 / 5S.,19.99,0,11865403,
196,KEN0063,Kensington Thin Back Case iPhone 5 / 5S Pink,Back Case iPhone 5 / 5S.,19.99,0,11865403,
197,MUV0042,Clear Back Case Muvit iPhone / 5s / 5 transparent,iPhone back cover tranparente SE / 5s / 5.,9.99,0,11865403,
199,MUV0047,Muvit MiniGel Funda iPhone 5 / 5S White,Rubber cover iPhone 5 / 5S.,8.99,0,11865403,
200,MUV0053,Muvit Slim case iPhone 5 / 5S purple,Imiatación Leather Case Cover for iPhone 5 / 5S.,14.99,0,11865403,
203,CYG0042,Cygnett UrbanShield Hard Case for iPhone 5 / 5...,Hard Case + Silver Storm screensaver iPhone 5 ...,19.99,1,11865403,
253,PUR0067,Puro iPhone Bumper Case SE / 5s / 5 black,IPhone Silicone Bumper SE / 5s / 5 transparent...,16.99,0,11865403,
254,PUR0075,Puro Booklet iPhone Case SE / 5s / 5 white,Eco leather book cover close iPhone SE / 5s / ...,11.99,0,11865403,
256,MOS0078,Moshi iGlaze iPhone Case SE / 5s / 5 Black,rigid shell with silver rim iPhone SE / 5s / 5,30.00,1,11865403,
257,MOS0080,Moshi iGlaze iPhone Case SE / 5s / 5 white,hard case for iPhone SE / 5s / 5,30.00,0,11865403,
258,MOS0082,Moshi iGlaze XT iPhone Case SE / 5s / 5 transp...,Rigid shell snap on iPhone SE / 5s / 5.,30.00,1,11865403,
361,TWS0046,Twelve South BookBook Case iPhone 5 / 5S black,Funda iPhone 5 / 5S vintage leather with padde...,49.99,0,11865403,
371,MOS0087,Moshi iGlaze iPhone case Kamaleon SE / 5s / 5 ...,IPhone Case SE / 5s / 5 with sleek aluminum su...,55.00,0,11865403,
373,NTE0045,NewerTech NuGuard KX iPhone Case SE / 5s / 5 B...,IPhone Case SE / 5s / 5 ultra resistant for ex...,60.99,1,11865403,
374,NTE0046,NewerTech NuGuard KX iPhone Case SE / 5s / 5 W...,IPhone Case SE / 5s / 5 ultra resistant for ex...,60.99,1,11865403,
433,JMO0044,Just Mobile AluFrame Alumino Bumper iPhone 5 /...,Aluminum Bumper iPhone 5 / 5S resistant.,49.99,0,11865403,
459,BEL0139,Belkin Lego iPhone Case SE / 5s / 5 Blue / Purple,Lego rigid shell for iPhone SE / 5s / 5.,29.99,0,11865403,
463,MUV0101,Muvit iPhone 5C Transparent Crystal Case,transparent housing for iPhone 5C.,9.99,0,11865403,
465,MUV0108,Muvit Slim Case + Screen Protector iPhone 5C W...,Slim Case + Screen Protector for iPhone 5C.,13.99,0,11865403,
475,TYL0015,TYLT Energi Sliding Power Battery Case iPhone ...,Case with 2500mAh Battery for iPhone SE / 5s / 5.,79.99,0,11865403,
499,GRT0300,Griffin Reveal iPhone Case SE / 5s / 5 Black,Bumper Black iPhone SE / 5s / 5 with transpare...,19.99,1,11865403,
554,NTE0055,NewerTech NuGuard KX iPhone Case SE / 5s / 5 B...,IPhone Case SE / 5s / 5 ultra resistant for ex...,60.99,1,11865403,
569,MOS0102,Moshi iGlaze Armor iPhone Case SE / 5s / 5 Plata,IPhone Case SE / 5s / 5 with sleek aluminum su...,45.00,0,11865403,
570,MOS0103,Moshi iGlaze Armor iPhone Case SE / 5s / 5 Bronze,IPhone Case SE / 5s / 5 with sleek aluminum su...,45.00,0,11865403,
574,NTE0058,NewerTech NuGuard KX Darkness Case iPhone 4 / ...,Case iPhone 4 / 4S ultra resistant for extreme...,60.99,1,11865403,
602,MUV0123,Muvit elastic belt with waterproof pocket Black,Muvit belt / shoulder bag with waterproof pock...,19.99,0,11865403,
640,UAG0008,Urban Armor Gear Composite Case Scout iPhone 5...,ultra durable and lightweight housing for iPho...,34.95,0,11865403,
651,KUA0007,Support Kukaclip car + Funda iPhone 5 / 5S Black,Magnetic car holder with 360 more housing rota...,24.99,0,11865403,
654,KUA0008,Support Kukaclip car + Case iPhone 4 / 4S Black,Magnetic car holder with 360 more housing rota...,14.99,0,11865403,
662,PUR0107,Puro Just Cavalli Swan iPhone Case Passion / 5...,IPhone anti-shock housing for iPhone SE / 5s / 5.,19.99,0,11865403,
678,MOS0115,Moshi SenseCover iPhone Case SE / 5s / 5 Black,Case for iPhone touch sensor SE / 5s / 5,45.00,0,11865403,
679,MOS0114,Moshi SenseCover iPhone Case SE / 5s / 5 Titanium,Case for iPhone touch sensor SE / 5s / 5,45.00,0,11865403,
680,UAG0010,Urban Armor Gear Composite Case iPhone Scout S...,ultra durable and lightweight for iPhone SE / ...,34.95,0,11865403,
721,INC0232,Focal Incipio iPhone Case Camera Case SE / 5s ...,Housing for perfect photo to iPhone SE / 5s / ...,59.99,0,11865403,
771,MUV0127,Muvit elastic belt with yellow raincoat pocket,Muvit belt / shoulder bag with waterproof pock...,19.99,0,11865403,
796,LIF0034,Lifeproof nüüd iPhone Case SE / 5s / 5 Waterpr...,IPhone Case SE / 5s / 5 waterproof and extreme...,89.99,0,11865403,
805,OPU0010,Exo Opulus alcantara iPhone Case SE / 5s / 5 B...,Cover for iPhone SE / 5s / 5 polycarbonate and...,39.99,0,11865403,
806,OPU0007,Opulus alcantara Executive Case iPhone 5 / 5S ...,Case for iPhone 5 / 5S polycarbonate and micro...,39.99,0,11865403,
809,OPU0009,Exo Opulus alcantara Case iPhone 5 / 5S black,Case for iPhone 5 / 5S polycarbonate and micro...,39.99,0,11865403,
819,BOO0078,Booq Case + Tempered Glass iPhone 5 / 5S Black,Semitransparent Hard Case + Protector tempered...,23.90,0,11865403,
836,AII0051,Aiino Bumper iPhone SE / 5s / 5 Green and Fuch...,2 Kit resistant bumpers for iPhone SE / 5s / 5.,17.99,0,11865403,
848,NON0007,Yoko Ono Non Violence Case iPhone 5 / 5S White,Yoko Ono hard case design for iPhone 5 / 5S.,14.99,0,11865403,
849,DIR0007,Dirty Velvet Busker Bear Case iPhone 5 / 5S White,Hard Shell with Busker Bear design for iPhone ...,14.99,0,11865403,
933,KUA0009,Support Kukaclip car + iPhone Case SE / 5s / 5...,Magnetic car holder with 360 more housing rota...,24.99,0,11865403,
934,MUV0139,Muvit Slim Case + Screen Protector iPhone 6 Black,Cover with lid and screen Protector iPhone 6 4...,14.99,0,11865403,
936,MUV0131,Muvit Crystal Folio iPhone 6 Green,Soft polyurethane cover with lid for iPhone 6 ...,19.99,0,11865403,

And here we can assign a category to the one we pick above:

In [32]:
category_type_df.loc[category_type_df["type"] == top_type.index[0], "category"] = "OWC"

WHICH WOULD HAVE GEEN A GREAT IDEA; BUT THE POSITIONS 2-4 are fucking mixed or? is something fucked with my code?